name: Simple OWASP ZAP Scan (Logs Only)

on: push
 # workflow_dispatch:

permissions:
   contents: read

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan (logs only)
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: "http://testphp.vulnweb.com/login.php"
          allow_issue_writing: false     # prevents GitHub issues
          #artifact_name: ""              # DISABLES artifact upload
          cmd_options: ""                # prevents zap.yaml permission issue
          # fail_action: false             # scan will not fail the job
